### ISSUE TITLE
Some test cases time out on the AppVeyor windows build

### ISSUE THREAD

**Issue by sfranzen** [sfranzen/ismcsolver#8]
Find out why!

**Comment by sfranzen** [comment]
Some of the issues have now been resolved in the win-build-fixes branch. Remaining issue is with parallel execution, where appveyor does not have pthread and this causes undefined behaviour in the parallel solver tests.

**Comment by DJuego** [comment]
I work in Windows 10 x64 with Microsoft Visual Studio 2017. If you want I can do a test for you...

DJuego

**Comment by sfranzen** [comment]
That would certainly be helpful. I currently only have this information to go by, though:
* Both single and multithreaded solvers use `std::thread` objects, one per thread;
* On my Linux system, `<thread>` is provided by pthreads and all solvers pass the simple test at the end of "test/solvertest.cpp";
* The Appveyor Windows environment uses VS2017 and the native windows threads implementation, the win-build-fixes branch builds successfully but tests of parallel solvers fail with what looks like undefined behaviour: https://ci.appveyor.com/project/sfranzen/ismcsolver/builds/24075478;

That means it is fine with vectors holding a single thread object and a single tree structure, but somehow gets into trouble when there is one of both for each system thread.

**Comment by DJuego** [comment]
Sorry for my very delayed answer. :-/

I have a Windows 10 x64 with MSVC 2017.

I have test the last master (20190508). I follow your instructions in [https://ci.appveyor.com/project/sfranzen/ismcsolver/builds/24075478](https://ci.appveyor.com/project/sfranzen/ismcsolver/builds/24075478)

I get the attached picture.
![2019-05-07_235935](https://user-images.githubusercontent.com/1956212/57338374-04d04f00-7125-11e9-8b5e-dc996feb3b7b.png)


DJuego

**Comment by DJuego** [comment]
Update: 2019-05-10
![2019-05-10_213449](https://user-images.githubusercontent.com/1956212/57555425-28390b00-736c-11e9-8251-5527bc532960.png)

DJuego

**Comment by sfranzen** [comment]
Indeed, those are the same messages I get. But I would like to find out how the 4 RootParallel tests come up with an answer like -572662307 where the available numbers were from 0 to 8.

**Comment by DJuego** [comment]
Well. I am sorry I can not offer you more help at the moment but I want you to know that I am **happy** for your continuous support to the project.

Something new. With this last master there are no errors in the executable compiled by visual Studio 2017 "manually".

![2019-05-19_224337](https://user-images.githubusercontent.com/1956212/57988553-9d50c280-7a87-11e9-8165-31e79e241d38.png)


However, when i follow your steps:


![2019-05-19_223825](https://user-images.githubusercontent.com/1956212/57988558-a80b5780-7a87-11e9-827d-cbe53256c984.png)

:-(

DJuego

**Comment by sfranzen** [comment]
I've found the error, it was a silly case of returning a reference to an object that goes out of scope.

**Comment by DJuego** [comment]
Well. I can confirm this! Congrats and thanks!! :-)
![2019-05-26_135551](https://user-images.githubusercontent.com/1956212/58382128-3a4ab880-7fbe-11e9-88eb-7e0a8a6f2d85.png)

DJuego
